// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUhZj2e8303EHmIKeJy_cNyPxpKfJly_8',
    appId: '1:1027622692473:web:95aeb0288ca76d79c796a8',
    messagingSenderId: '1027622692473',
    projectId: 'fypproject-2d894',
    authDomain: 'fypproject-2d894.firebaseapp.com',
    storageBucket: 'fypproject-2d894.appspot.com',
    measurementId: 'G-TFT6NS6KS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFQHLHkgWjPvvunYtCz9B259tHLboiQxQ',
    appId: '1:1027622692473:android:7b0e465bc1fea1e7c796a8',
    messagingSenderId: '1027622692473',
    projectId: 'fypproject-2d894',
    storageBucket: 'fypproject-2d894.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDRFpwLbhUw4p5S60EPExNBdHI4yyJ2Kc',
    appId: '1:1027622692473:ios:f7cdd18933716520c796a8',
    messagingSenderId: '1027622692473',
    projectId: 'fypproject-2d894',
    storageBucket: 'fypproject-2d894.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDRFpwLbhUw4p5S60EPExNBdHI4yyJ2Kc',
    appId: '1:1027622692473:ios:3492495ea13d2c8dc796a8',
    messagingSenderId: '1027622692473',
    projectId: 'fypproject-2d894',
    storageBucket: 'fypproject-2d894.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
